lt-cred-mech
use-auth-secret
static-auth-secret=zonvo_turn_dev_secret
realm=zonvo.local
server-name=coturn
listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
log-file=/var/log/coturn/turnserver.log
verbose
no-cli
